import 'i_filter.dart';

class ZacatrusEditorialFilter implements ISingleFilter {
  @override
  final String value;

  const ZacatrusEditorialFilter({
    required this.value,
  });

  ZacatrusEditorialFilter.url({
    required String valueUrl,
  }) : value = categoriesUrl.keys.firstWhere((key) => categoriesUrl[key] == valueUrl);

  static Iterable<String> get categories => categoriesUrl.keys;

  static Map<String, String> categoriesUrl = {
    "Zacatrus": "zacatrus",
    "2 Tomatoes": "2_tomatoes",
    "2D10 Games": "2d10_games",
    "Abba Games": "abba_games",
    "Afrogames": "afrogames",
    "Alea": "alea",
    "Amphora Games": "amphora_games",
    "Anima-T": "anima_t",
    "Ankama": "ankama",
    "APA Boardgames": "apa_boardgames",
    "Aquamarine": "aquamarine",
    "Archon Studio": "archon_studio",
    "Ares games": "ares_games",
    "Arquitectura a contrapelo": "arquitectura_a_contrapelo",
    "Arrakis Games": "arrakis_games",
    "Artipia Games": "artipia_games",
    "Asmodée": "asmodee",
    "Asylum Games": "asylum_games",
    "Átomo Games": "atomo_games",
    "Aurora": "aurora",
    "Avalon Hill": "avalon_hill",
    "Bad Comet": "bad_comet",
    "Bananagrams": "bananagrams",
    "Bezier Games": "bezier_games",
    "Bioviva": "bioviva",
    "Blauberry": "blauberry",
    "Blue Orange": "blue_orange",
    "Brain Picnic": "brain_picnic",
    "Bridge Bandit": "bridge_bandit",
    "Bumble3ee": "bumble3ee",
    "Burning Games": "burning_games",
    "Buró de Juegos": "buro_de_juegos",
    "Cacahuete Games": "cacahuete_games",
    "Caracol Juegos de Mesa": "caracol_juegos_de_mesa",
    "Cayro": "cayro",
    "Cerebrer Games": "cerebrer_games",
    "CGE - Czech Games Edition": "cge_czech_games_edition",
    "Chilifox Games": "chilifox_games",
    "Circoctel": "circoctel",
    "Class Games": "class_games",
    "CMON": "cmon",
    "Cocktail Games": "cocktail_games",
    "Cojones Games": "cojones_games",
    "ConBarba": "conbarba",
    "Corvus Belli": "corvus_belli",
    "Cosplay Original": "cosplay_original",
    "Crazy Pawn": "crazy_pawn",
    "Ctrlaltcreative": "ctrlaltcreative",
    "Darbel": "darbel",
    "Days of Wonder": "days_of_wonder",
    "Delirium Games": "delirium_games",
    "Devir": "devir",
    "Diset": "diset",
    "Dizemo": "dizemo",
    "Djeco": "djeco",
    "DMZ games": "dmz_games",
    "Do It": "do_it",
    "Draco Ideas": "draco_ideas",
    "Druid City Games": "druid_city_games",
    "Eagle Games": "eagle_games",
    "Eclipse Editorial": "eclipse_editorial",
    "Edge Entertainment": "edge_entertainment",
    "Ediciones Primigenio": "ediciones_primigenio",
    "Edigrafica": "edigrafica",
    "Educa": "educa",
    "El Troquel": "el_troquel",
    "En Movimiento 360": "en_movimiento_360",
    "Enpeudejoc Edicions": "enpeudejoc_edicions",
    "Enuntris": "enuntris",
    "Excalibur": "excalibur",
    "Exploding Kittens": "exploding_kittens",
    "Extended Play": "extended_play",
    "Falomir": "falomir",
    "Fantasy Flight": "fantasy_flight",
    "Ferti": "ferti",
    "Fesme Games": "fesme_games",
    "Flying Frog Production": "flying_frog_production",
    "Fractal Juegos": "fractal_juegos",
    "Funko": "funko",
    "Gabinete Lúdico": "gabinete_ludico",
    "Gale Force Nine": "gale_force_nine",
    "Game Brewer": "game_brewer",
    "Games for Gamers": "games_for_gamers",
    "Games Workshop": "games_workshop",
    "GDM Games": "gdm_games",
    "Gen X Games": "gen_x_games",
    "Gigamic": "gigamic",
    "Giochi Uniti": "giochi_uniti",
    "Giochix": "giochix",
    "GMT": "gmt",
    "Gnomosaurus": "gnomosaurus",
    "Goliath": "goliath",
    "Haba": "haba",
    "Hasbro": "hasbro",
    "Haus of Glitter": "haus_of_glitter",
    "Holocubierta": "holocubierta",
    "Holy Grail Games": "holy_grail_games",
    "Homoludicus": "homoludicus",
    "Huch & Friends": "huch_friends",
    "Hurrican Games": "hurrican_games",
    "IDW Games": "idw_games",
    "Iello": "iello",
    "invedars": "invedars",
    "JAM": "jam",
    "Juegorama": "juegorama",
    "Julibert": "julibert",
    "Kibo": "kibo",
    "Kodomo": "kodomo",
    "Kosmos": "kosmos",
    "Koti Games": "koti_games",
    "La Mame Games": "la_mame_games",
    "La Pinta Games": "la_pinta_games",
    "Last Level": "last_level",
    "Libellud": "libellud",
    "Longalive Games": "longalive_games",
    "Lookout Games": "lookout_games",
    "Looping Games": "looping_games",
    "Lucky Duck Games": "lucky_duck_games",
    "Ludic": "ludic",
    "Ludically": "ludically",
    "Ludilo": "ludilo",
    "Ludoismo": "ludoismo",
    "Ludonaute": "ludonaute",
    "Ludonova": "ludonova",
    "LudoSentinel": "ludosentinel",
    "Ludotecnia": "ludotecnia",
    "Lui-Méme": "lui_meme",
    "Magic Box Games": "magic_box_games",
    "Maldito Games": "maldito_games",
    "MasQueOca": "masqueoca",
    "Matagot": "matagot",
    "Mattel": "mattel",
    "Mebo": "mebo",
    "Megacorpin Games": "megacorpin_games",
    "Melmac Games": "melmac_games",
    "Mercurio": "mercurio",
    "Meridiano 6": "meridiano_6",
    "Mixingames": "mixingames",
    "Mont Taber": "mont_taber",
    "Mystical Games": "mystical_games",
    "Next Move": "next_move",
    "No game over": "no_game_over",
    "Nosolorol": "nosolorol",
    "Nostromo Games": "nostromo_games",
    "Oink Games": "oink_games",
    "Paizo": "paizo",
    "Pavana Games": "pavana_games",
    "Pearl Games": "pearl_games",
    "Pegasus Spiele": "pegasus_spiele",
    "Peka": "peka",
    "Pendragon": "pendragon",
    "Perro Loko Games": "perro_loko_games",
    "Petersen Games": "petersen_games",
    "Pinbro Games": "pinbro_games",
    "PiroJoc": "pirojoc",
    "Plaid Hat Games": "plaid_hat_games",
    "Plan B Games": "plan_b_games",
    "PlastCraft Games": "plastcraft_games",
    "Portal Publishing": "portal_publishing",
    "Pythagoras": "pythagoras",
    "Queen Games": "queen_games",
    "Qworkshop": "qworkshop",
    "R&R Games": "r_r_games",
    "Ravensburger": "ravensburger",
    "Rebel": "rebel",
    "Red Glove": "red_glove",
    "Repos Production": "repos_production",
    "República Bananera": "republica_bananera",
    "Reverse Games": "reverse_games",
    "Rio Grande Games": "rio_grande_games",
    "Road to Infamy": "road_to_infamy",
    "Rocket Lemon Games": "rocket_lemon_games",
    "Salt & Pepper Games": "salt_pepper_games",
    "Scale Games": "scale_games",
    "Schmidt": "schmidt",
    "Scorpion Masqué": "scorpion_masque",
    "SD Games": "sd_games",
    "Shining Creations": "shining_creations",
    "Smart Troll Games": "smart_troll_games",
    "SmartPlay": "smartplay",
    "SombraDist": "sombradist",
    "Space Cowboys": "space_cowboys",
    "Steamforged Games LTD.": "steamforged_games_ltd",
    "Steve Jackson Games": "steve_jackson_games",
    "Synapses Games": "synapses_games",
    "T Tower Games": "t_tower_games",
    "TCG": "tcg",
    "Tetrakis": "tetrakis",
    "The Game Forger": "the_game_forger",
    "Thinkfun": "thinkfun",
    "Thundergryph Games": "thundergryph_games",
    "Tortugames": "tortugames",
    "Tranjis": "tranjis",
    "Txarly Factory": "txarly_factory",
    "Unexpected Games": "unexpected_games",
    "Van Ryder Games": "van_ryder_games",
    "Vedra": "vedra",
    "Viravi": "viravi",
    "White Goblin Games": "white_goblin_games",
    "Wizards of the Coast": "wizards_of_the_coast",
    "Wizkids": "wizkids",
    "Ystari Games": "ystari_games",
    "Z-Man Games": "z_man_games",
    "Zombi Paella": "zombi_paella",
    "Zygomatic": "zygomatic"
  };

  @override
  String? toUrl() {
    return categoriesUrl[value]!;
  }

  static bool isValidCategory(String category) {
    return categories.contains(category);
  }

  @override
  isValid() => isValidCategory(value);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ZacatrusEditorialFilter && runtimeType == other.runtimeType && value == other.value;

  @override
  int get hashCode => value.hashCode;
}
